### PR TITLE
Fix misspelling/typo in osa-docker.sh

### PR DESCRIPTION
**Pull request by esabol**
Simple PR to fix a misspelling/typo in osa-docker.sh. Thanks!

### CODE REVIEW

**Comment by esabol** [comment]
Hello? Anyone out there?

**Comment by esabol** [comment]
> Hello? Anyone out there?

I guess not. :(

**Comment by esabol** [comment]
Pinging @volodymyrss

**Comment by volodymyrss** [comment]
Sorry for such a long delay! Yes, pinging me worked.

Thanks for the fix!

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
